import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

// Loads and defines the custom fonts
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

// Metadata for layout for title and description
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Root layout components, wraps the entire application
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
