# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  check-do-not-merge-label:
    # check if "Do Not Merge" label is applied, and prevent merging if it is
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Check for "Do Not Merge" label
          command: |
            pr_number=$(echo $CIRCLE_PULL_REQUEST | awk -F '/' '{print $NF}')
            labels=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
            https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues/${pr_number}/labels)

            if echo "$labels" | grep -q "Do Not Merge"; then
              echo "Label 'Do Not Merge' is present. Failing the job."
              exit 1  # Fail the job if the label is present
            else
              echo "No 'Do Not Merge' label found. Proceeding."
            fi
  lint-python:
    docker:
      - image: cimg/python:3.9  # Use Python Docker image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r backend/requirements.txt
      - run:
          name: Run Flake8 on Python files
          command: |
            . venv/bin/activate
            flake8 backend/  # Only check Python files
  lint-frontend:
    docker:
      - image: cimg/node:16  # Use a compatible Node.js version for Next.js
    steps:
      - checkout
      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install
      # Run ESLint
      - run:
          name: Run ESLint
          command: npm run lint  # Ensure lint script exists in package.json
      # Run Prettier
      - run:
          name: Check Prettier formatting
          command: npm run prettier-check  # Ensure prettier-check script exists in package.json

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  tutor-u-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - check-do-not-merge-label
      - lint-python
      - lint-frontend
